Fix failures to configure RAID with newish dracclient
The "Ensure that DRAC configuration is applied" task was failing with
the following error:

    FAILED! => {"changed": false, "msg": "Failed to configure DRAC: AttributeError(\"'PhysicalDisk' object has no attribute 'raid_state'\",)"}

The raid_state attribute was deprecated back in 2016 [1]. It was then
removed in release 2.0.0, released in November 2018.

[1] https://opendev.org/openstack/python-dracclient/commit/9ff7c31
[2] https://opendev.org/openstack/python-dracclient/commit/3cb32a9